# RecSession

A recording session consists of several electrophysiological data files recorded from one animal on a given day.
All these files are in the same directory.
The name of the directory is the name of the recording session.
The session directory contains several data and configuration files. 
We will use the recroding session `jp19841-10072015-0108` as an example.
On my computer, the path of this directory is
`~/Downloads/data_relectro_doc/circular_arena/jp19841/jp19841-10072015-0108`

The directory of the recording session contains several files. You can list them from within R

```{R session_files}
list.files(path="~/Downloads/data_relectro_doc/circular_arena/jp19841/jp19841-10072015-0108")
```

If you want to know what information these files contain, have a look at the file `~/Downloads/data_relectro_doc/file_description`


One role of the RecSession object in *relectro* is to read several of these files to gather the properties of the recording session.
Instead of reading all these files while programing, you just need to create and load the RecSession object and get on with your work without having to directly interact with the files.

## Create a RecSession object


```{R methods,  echo = FALSE} 
library(methods)# this block is there so that we can use new()
```

Let's create a RecSession object to represent our recording session.

```{r RecSession}
library(relectro)
## assign the name of the session to a variable called session
session="jp19841-10072015-0108"
## assign the session directory to a variable called datadir
datadir="~/Downloads/data_relectro_doc/circular_arena/jp19841/jp19841-10072015-0108"
## create a RecSession object
rs<-new("RecSession",session=session,path=datadir)
## print the content of rs
print(rs)
```

Now we have an object called `rs` that represents our recording session.
However, most of the attributes in `rs` are not assigned.
To gather the properties of the recording session, you need to call the function `loadRecSession`.

```{R loadRecSession}
rs<-loadRecSession(rs)
```

Here, the result of the function `loadRecSession()` is assigned to `rs`.
The function `loadRecSession` returns a new RecSession object with all session properties.
If you print the new value of `rs` to the screen, you can read information regarding your recording session.

```{R print_rs}
print(rs)
```

You can now read that the sampling rate during this session was `r rs@samplingRate` Hz and that the lenght of the session was `r rs@sessionDurationSec` sec.

One side effect of calling the function `loadRecSession` is that it will check the validity of several configuration files that are create at recording time.
If there are inconsistencies between configuration files, an error message appears and indicates what the problem is. You will need to fix these inconsistencies with your favorite text editor.

## Attributes of RecSession objects

All classes in *relectro* are S4 classes. 
This means that you can access their attributes with `@`.
For example, you can get the sampling rate with `rs@samplingRate`. 
Here is how to get a list of all the attributes of an object in R.
```{R eval=FALSE}
attributes(rs)
## or
RecSession
```
Now that you have a list of the attributes, here is how you can access them.
```{R access_attributes}
rs@animalName
rs@nChannels
```

## Methods
Methods are functions that are part of a class (e.g. RecSession). To list the methods of the RecSession class
```{R RecSession_methods}
methods(class=RecSession)
```
As indicated in the output, see `?methods` for acessing help.
For example
```{R RecSession_help, eval=FALSE}
?recordingDate
```

The methods usually have a RecSession object as first argument.
``` {R RecSession_calling_method}
recordingDate(rs)
getIsClustered(rs)
containsElectrodeLocation(rs,location="ca1")
containsEnvironment(rs,environment="circ")
```

## Source code of methods
You can inspect the code of the method `recordingDate`.
```{R getMethod_recordingDate}
getMethod("recordingDate","RecSession")
```
This is very usefull if the method is not working as you expect and you want to understand why.

## Programing exercise

Here is a short exercise to apply what you have learned in this chapter.

You will explore a recording session from the linear_track project. In this experiment, there were 3 different environments. The animal could be either in an open field, in a rest box or on a linear track. You can find this information by looking at the `env` attribute of the RecSession object (`sqr70` for open field, `rest` for rest box, and `lt` for linear track).

What was the time spent on the linear track in the recording session called `jp4103-30032016-0107`? The code for linear track in the "env" attribute of the recording session is "lt". Below is the answer. See if you can get the same answer yourself.
```{R RecSessionExercise1,echo=FALSE}
session="jp4103-30032016-0107"
## assign the session directory to a variable called datadir
datadir="~/Downloads/data_relectro_doc/linear_track/jp4103/jp4103-30032016-0107"
## create a RecSession object
rs<-new("RecSession",session=session,path=datadir)
rs<-loadRecSession(rs)
print(paste(sum(rs@trialDurationSec[which(rs@env=="lt")]),"sec"))
```
Tip: you need to use the attributes `trialDurationSec` and `env`.

Keeping with the recording session `jp4103-30032016-0107`, what was the sampling rate?
```{R RecSessionExercise2,echo=FALSE}
print(paste(rs@samplingRate,"Hz"))
```

Get the time intervals in samples of the  begining and end of the trials with the linear track
```{R RecSessionExercise3,echo=F}
i<-which(rs@env=="lt")
print(paste(rs@trialNames[i],":",rs@trialStartRes[i],rs@trialEndRes[i]))
```
Tip: Have a look at the `trialStartRes` and `trialEndRes` attributes, or use `getIntervalsEnvironment()`. 

What is the recording date of this recording session? Tip: Use a method of the RecSession class.
```{R RecSessionExercise4,echo=F}
print(recordingDate(rs))
rm(session,datadir,rs,i)
```
