
# SpikeTrain
This chapter documents the use of the SpikeTrain class. 
A SpikeTrain object represents the spike trains of a group of neurons recorded in the same recording session. 
The spike trains are usually loaded from files containing the spike times in sample values, the id of the cell firing and the sampling rate. 
You have to call the function `loadSpikeTrain()` to read the data from the files. 
The 3 files from which the data are loaded have the extension `res`, `clu` and `sampling_rate_dat`. 

Note that you can also set the data manually with `setSpikeTrain()`. This feature is usefull if you want to work with simulated spike trains. 

Once a SpikeTrain object is set, you can use different functions to do analysis on the spike trains. 
For example, you can calculate spike-train autocorrelations using the function `spikeTimeAutocorrelation()`. 
You can also calculate the firing rate using `meanFiringRate()`.

## Create SpikeTrain objects 

We start be creating RecSession and SpikeTrain objects. The function to load the spike train into memory is called `loadSpikeTrain`.

```{r real_spike_trains}
library(relectro)
## assign the name of the session to a variable called session
session="jp19841-10072015-0108"
## assign the session directory to a variable called datadir
datadir="~/Downloads/data_relectro_doc/circular_arena/jp19841/jp19841-10072015-0108"
## create a RecSession object
rs<-new("RecSession",session=session,path=datadir)
rs<-loadRecSession(rs)
# create SpikeTrain object and load data
st<-new("SpikeTrain",session=rs@session,path=rs@path)
st<-loadSpikeTrain(st) # load res clu and sampling rate
print(st)
```

As with other objects, you can get a list of the attributes of your SpikeTrain object with `?SpikeTrain` and you can access them with `@`
```{R SpikeTrain_attributes}
?SpikeTrain
print(paste("Sampling rate of st", st@samplingRate, "Hz"))
print(paste("Number of cells in st:",st@nCells))
```

## Methods
List the methods of the SpikeTrain class
```{R methods_SpikeTrain}
methods(class=SpikeTrain)
```

## Mean firing rate
Use `meanFiringRate` to calculate the mean firing rate of neurons.
```{R meanFiringRate}
st<-meanFiringRate(st)
```
The method `meanFiringRate` returns a SpikeTrain object. This new SpikeTrain object is assigned to `st`.

You can access the firing rate values using `@`.
```{R print_meanFiringRate}
print(st@meanFiringRate)
```
This is the mean firing rate of all neurons in the SpikeTrain object for the entire recording session.

If you are curious and wants to see the code of the `meanFiringRate` method, use getMethod.
```{R seeCode}
getMethod("meanFiringRate","SpikeTrain")
```
In this method, there is a call to the `.Call()` function. 
This means that the firing rate is calculated using c code instead of within R. 
The first argument of `.Call()` is `meanFiringRate_cwrap`, which is the name of a c function.
If you have the source code of *relectro*, all c functions are defined in the directory `src`.

## Limit analysis to time intervals

It is often useful to limit the analysis to specific parts of the recording session.
Time intervals are used for this purpose.
Time is in sample values and not in seconds.

To limit the analysis to some time intervals, you need to set these intervals in the SpikeTime object.
By default, the intervals in the SpikeTime object are set from the beginning to the end of the recording session.
```{R setIntervals}
print(st)
```
You can see that there is `r length(st@startInterval)` interval set by default.
Now we set the intervals to the second trial of the recording session.
We use the RecSession object to get the start and end time of the second trial.
The method `setIntervals` of the SpikeTime class let you set these intervals in a SpikeTime object.
```{R setIntervals2}
st2<-setIntervals(st,rs@trialStartRes[2],rs@trialEndRes[2])
print(st2)
```
Now we have one interval of `r sum(st@endInterval-st@startInterval)/st@samplingRate` seconds in the `st` object.
If you now recalculate the mean firing rate of the neurons, the analysis will be limited to the data within this interval.

```{R setIntervals3}
st2<-meanFiringRate(st2)
print(st2@meanFiringRate)
```


You could calculate the difference in firing rate between the second and third trials. 
```{R compareMeanFiringRate}
## get a SpikeTrain object with intervals set at 3rd trial
st3<-setIntervals(st,rs@trialStartRes[3],rs@trialEndRes[3])
## get firing rate with SpikeTrain, limited to 3rd trial
st3<-meanFiringRate(st3)
print(st3@meanFiringRate)
## print the difference in firing rate between 
## trial 2 and 3
st3@meanFiringRate-st2@meanFiringRate
```

### Time intervals from files

Sometimes the intervals to limit the analysis are stored in a file located in the recording session directory.
For example, in the circular_arena database, there is a file with the extension `light_trials_intervals` in each recording session directory. We will get its content by reading the file.
```{R SpikeTrainIntervalFile}
# get the file name from the RecSession object
fileName<-paste(rs@fileBase,"light_trials_intervals",sep=".")
df<-read.table(fileName,header=F) # read into a data.frame
colnames(df)<-c("trialNo", "condition","start","end") # set the column name to simplify the code below
head(df)
```

We now calculate the firing rate for periods in which the condition was `l1`.

```{R SpikeTrainFile2}
st.l1<-setIntervals(st,
                 s=df$start[which(df$condition=="l1")],
                 e=df$end[which(df$condition=="l1")])
print(st.l1) ## check the number of intervals and interval time
st.l1<-meanFiringRate(st.l1)
print(st.l1@meanFiringRate)
rm(df,st.l1) # delete objects that we don't need anymore.
```



## Limit analysis to specific cells

It is sometimes useful to perform analysis on a subset of cells. 
For example, you could want to analyze only cells with a firing rate higher than 2 Hz during the second trial.
All you have to do is to set the attribute `cellList` in the SpikeTrain object.
By defaut, the `cellList` attribute of the SpikeTrain object includes all recorded neurons.
```{R setCellList}
## set intervals to 2nd trial (was already set to these intervals)
st2<-setIntervals(st,rs@trialStartRes[2],rs@trialEndRes[2])
print(st2@cellList)
## which cells have mean friring rate above 2 in 2nd trial
st2@meanFiringRate>2
## get the cluster number of these cells
st2@cellList[st2@meanFiringRate>2]
## set the new cellList in the st object
st2<-setCellList(st2,st@cellList[st2@meanFiringRate>2])
print(st2@cellList)
## now analysis will be performed only on these cells
## get the firing rate during the fourth trial
st4<-setIntervals(st,rs@trialStartRes[4],rs@trialEndRes[4])
st4<-meanFiringRate(st4)
print(st4@meanFiringRate)
```


## Spike-time autocorrelation

In a spike-time autocorrelation, Each spike is treated in turn as a reference spike. The number of spikes or probability to observe a spike around the reference spike is calculated.

Here, we calculate the spike-time autocorrelation for the entire recording session and for all neurons.
You can set the window size and the bin size in ms for the spike-time autocorrelation.
The results are in the `auto` attribute of the SpikeTrain object.
```{R spikeTimeAutocorrelation}
st<-spikeTimeAutocorrelation(st,binSizeMs = 1,windowSizeMs = 10,probability = F)
## print the spike-time autocorrelation from the SpikeTrain object
print(st@auto)
```

Let's plot the spike-time autocorrelation of the first cluster in the SpikeTrain object.

```{R spikeTimeAutocorrelationPlot}
st<-spikeTimeAutocorrelation(st,binSizeMs = 1,windowSizeMs = 300,probability = F)
plot(st@autoTimePoints,st@auto[,1],type='l',
     ylab="Spike counts",xlab="Time (ms)")
```

The bumps near 125 ms are caused by theta oscillations. 
The spike counts near time 0 are very low because of the refractory period of the neuron.
You can zoom in on the refractory period by changing the time window of the spike-time autocorrelation.

```{R spikeTimeAutocorrelationPlot1}
st<-spikeTimeAutocorrelation(st,binSizeMs = 1,windowSizeMs = 30,probability = F)
plot(st@autoTimePoints,st@auto[,1],type='l',
     ylab="Spike counts",xlab="Time (ms)")
```

## Spike-time crosscorrelation between cells

You can calculate spike-time crosscorrelations in a similar way. In this case, the spikes of one neuron are used as reference spikes for a second neuron.

```{R spikeTimeCrosscorrelation}
st<-spikeTimeCrosscorrelation(st,binSizeMs=1,windowSizeMs = 5,probability = T)
st@cross
```

There are more crosscorrelation than cells in this case because there is a crosscorrelation for each cell pair in the SpikeTrain object. Here is how to get the identity of the cell in each pair
```{R spikeTimeCrosscorrelation2}
print(st@cellPairList)
```

Here is a plot of one crosscorrelation

```{R spikeTimeCrosscorrelation3}
st<-spikeTimeCrosscorrelation(st,binSizeMs=1,windowSizeMs = 300,probability = F)
plot(st@crossTimePoints,st@cross[,6],type='l',
     xlab="Time (ms)",ylab="Spike count",
     ylim=c(0,max(st@cross[,6])),
     main=paste("Pair:",st@cellPairList[6,1],st@cellPairList[6,2]))
```


## Spike-time crosscorrelation to events

If you want to do a spike-time crosscorrelation to a series of time points (or events), first set events in the SpikeTrain object and then call the method `spikeTimeCrosscorrelationEvents`.

```{R spikeTimeCrosscorrelation4}
## set some events
st<-setEvents(st,events=seq(0,2000000,1000))
st<-spikeTimeCrosscorrelationEvents(st,binSizeMs=1,windowSizeMs = 10,probability = F)
## results are in st@crossEvents
```

## Instantaneous firing rate

The instantaneous firing rate is often used to correlate the rate of a neuron to another rapidely varying variable (running speed, theta power, etc.).
There are a few steps involved in calculating the instantaneous firing rate. 
First, a vector with the number of spike in each bin is calculated. 
Second, a Gaussian kernel is apply to the spike count vector. 
Third, the firing probability is then integreted over a set window size. 
Finally, the firing probability is transformed into a firing rate.

A second common use of the instantaneous firing rate is to look at firing associations between pairs of neurons. We will calculate these correlation here.

```{R ifr}
## calculate the ifr
st<-ifr(st,windowSizeMs = 100, spikeBinMs = 1,kernelSdMs = 100)
## ifr is stored as a matrix
class(st@ifr)
dim(st@ifr)

## plot the instantaneous firing rate of two neurons
plot(st@ifrTime[1:1000],st@ifr[5,1:1000],type='l', 
     ylab="Rate (Hz)",xlab="Time (sec)")
lines(st@ifrTime[1:1000],st@ifr[1,1:1000],col="red")
## get the ifr associations between pairs of neurons
ifrAssociation(st)
```

There is a correlation coefficient for each cell pair.

## Simulated spike trains

The SpikeTrain object can be used with simulated spike trains or to analyze trains of events that are not necessarily spikes!

Here is how you would simulate the spike trains of 3 neurons. Their firing activity follows a poisson process.

```{R simu}
## generate spikes for 3 neurons
res1<-cumsum(rpois(n=1000,lambda=10))
res2<-cumsum(rpois(n=1000,lambda=15))
res3<-cumsum(rpois(n=1000,lambda=20))
clu<-c(rep(1,1000),rep(2,1000),rep(3,1000))
df<-data.frame(res=c(res1,res2,res3),clu=clu)
df<-df[order(df$res),] # sort according to res values

## create a SpikeTrain object from random spikes ###
st<-new("SpikeTrain")
## set the spike trains in the object
st<-setSpikeTrain(st=st,res=df$res,clu=df$clu,samplingRate=20000)

## get the spike-time autocorrelation
st<-spikeTimeAutocorrelation(st,binSizeMs=10,windowSizeMs=500,probability = F)
## plot the autocorrelation
plot(st@autoTimePoints,st@auto[,1],
     ylim=c(0,max(st@auto[,1])),
     type='l',ylab="Spike count", xlab="time (ms)")
lines(st@autoTimePoints,st@auto[,2],col="red")
lines(st@autoTimePoints,st@auto[,3],col="blue")
## get the mean firing rate
st<-meanFiringRate(st)
print(st@meanFiringRate)
rm(clu,res1,res2,res3,df,st)
rm(st1,st2,st3,st4)
```


## Programming exercises

As there is nothing like learning by doing, here are a few exercises that review what has been presented in this chapter. 

We will work on the recording session called `jp4103-30032016-0107` from the linear_track experiment. 
First create the RecSession and SpikeTrain objects for this session. Load the information from the files for both objects.

```{R SpikeTrainExercise1,echo=FALSE}
session="jp4103-30032016-0107"
datadir="~/Downloads/data_relectro_doc/linear_track/jp4103/jp4103-30032016-0107"
rs<-new("RecSession",session=session,path=datadir)
rs<-loadRecSession(rs)
st<-new("SpikeTrain",session=rs@session,path=rs@path)
st<-loadSpikeTrain(st) # load res clu and sampling rate
```

Print the mean firing rate of all the neurons of the recording session for all trials during which the animal was on the linear track.

```{R SpikeTrainExercise2,echo=FALSE}
st<-setIntervals(st,s=rs@trialStartRes[which(rs@env=="lt")],
             e=rs@trialEndRes[which(rs@env=="lt")])
st<-meanFiringRate(st)
print(st@meanFiringRate)
```
Tip: You need to get the start and end intervals for the trials in which the animal was on the linear track, set the intervals in the SpikeTrain object, and get the mean firing rate.

Calculate the spike-time autocorrelation of the neuron with the cluster id `2` for trials on the linear track and trials in the rest box. The autocorrelation should have bins of 2 ms and extend from -400 to 400 ms. Use probability instead of spike count.

Plot the results to compare the two spike-time autocorrelation.

```{R SpikeTrainExercise3,echo=F}
st<-setCellList(st,cellList = 2)
st<-setIntervals(st,s=rs@trialStartRes[which(rs@env=="lt")],
             e=rs@trialEndRes[which(rs@env=="lt")])
st<-spikeTimeAutocorrelation(st,binSizeMs = 2,windowSizeMs = 400,probability = T)
auto.lt<-st@auto
st<-setIntervals(st,s=rs@trialStartRes[which(rs@env=="rest")],
             e=rs@trialEndRes[which(rs@env=="rest")])
st<-spikeTimeAutocorrelation(st,binSizeMs = 2,windowSizeMs = 400,probability = T)
plot(st@autoTimePoints,st@auto,type='l',
     xlab="Time (ms)",ylab="Spike probability")
lines(st@autoTimePoints,auto.lt,col="red")
legend(x=-300, y = 0.2,legend = c("Rest","Lin. track"),col=c(1,2),lwd=1,bty="n")
```

Notice the stronger theta rhythmicity during trials on the linear track.
