# Recording session summary figure

This page shows you how to get a summary figure for the neurons you recorded during a single recording session.
It might be interesting to get this output just after you clustered your recording session to know what cell types you have at the tip of your tetrodes.


We start with a recording session.
```{R summaryFig}
library(relectro)
## assign the name of the session to a variable called session
session="jp4311-09032016-0107"
## assign the session directory to a variable called datadir
datadir="~/Downloads/data_relectro_doc/linear_track/jp4311/jp4311-09032016-0107/"
## create a RecSession object
rs<-new("RecSession",session=session,path=datadir)
rs<-loadRecSession(rs)

myList<-getRecSessionObjects(rs)
st<-myList$st
pt<-myList$pt
cg<-myList$cg
sp<-myList$sp
hd<-myList$hd
```

Now we decide on what we want to display.
Let say we want two spike-time autocorrelations, spikeOnPlot, firing rate map, spatial autocorrelation and head-direction polar plot for each neuron.
```{R summaryFig2}
ptsqr70<-setInvalidOutsideInterval(pt,s=getIntervalsEnvironment(rs,env="sqr70")[,1],
                                   e=getIntervalsEnvironment(rs,env="sqr70")[,2])

# no interval set in st, so analysis based on all recording session
st<-spikeTimeAutocorrelation(st,binSizeMs = 1,windowSizeMs = 30,probability = FALSE)
st1<-spikeTimeAutocorrelation(st,binSizeMs = 2,windowSizeMs = 400,probability = FALSE)
# ptsqr70 is limited to sqr70, so analysis limited to this
sop<-spikeOnPath(sp,st,ptsqr70)
#
sp<-firingRateMap2d(sp,st,ptsqr70)
sp<-mapSpatialAutocorrelation(sp)
#
hd<-headDirectionHisto(hd,st,ptsqr70)
```

## Split screen
We have all the data needed, now we just need to make the plots.
Since we have several plots on the same figure, we use `split.screen()` to do this. 
We will first do the analysis for one neuron to start with a simple example.
We will split the graphic device into 6 screens for our figures.

```{R summaryFig3}
# prepare a matrix that indicates how to split the screen, the values range from 0 to 1
# each line of 4 numbers is minX, maxX, minY, maxY
m<-matrix(c(c(0.00,0.33,0.50,1.00),
        c(0.33,0.66,0.50,1.00),
        c(0.66,1.00,0.50,1.00),
        c(0.00,0.33,0.00,0.50),
        c(0.33,0.66,0.00,0.50),
        c(0.66,1.00,0.00,0.50)),ncol = 4,byrow = TRUE)
print(m)
## split our screen 
split.screen(m)

## select a cluster
selCluster<-2

## select the first screen
screen(1)
## plot
spikeTimeAutocorrelationPlot(x=st@autoTimePoints,
                             y=st@auto[,which(st@cellList==selCluster)],type='l')
## move to next screen and plot
screen(2)
spikeTimeAutocorrelationPlot(x=st1@autoTimePoints,
                             y=st1@auto[,which(st@cellList==selCluster)],type='h')
screen(3)
spikeOnPathPlot(sop,clu=selCluster)
screen(4)
firingRateMapPlot(sp@maps[,,which(sp@cellList==selCluster)])
screen(5)
firingRateMapAutoPlot(sp@autos[,,which(sp@cellList==selCluster)])
screen(6)
headDirectionPolarPlot(hd@histo[,which(hd@cellList==selCluster)])
## close the screens and close the devise
close.screen(all = TRUE)
# If you want to see the figure, wait before running dev.off()
dev.off()
```

## Summary figure of a recording session

Let say you just completed clustering the spikes of one recording session and want to generate 
a summary figure for all cells recorded during this recording session.
A flexible way is to create a function to generate this figure for a single recording session.
Here is an example of function.

```{R summaryFig4, eval=FALSE}
## function to generate a pdf file with the recorded neurons of one recording session
## we want to display 2 spike-time autocorrelation and 2 maps for each neuron
## one neuron per row
recSessionSummaryPlot<-function(rs){
  myList<-getRecSessionObjects(rs)
  pt<-myList$pt
  st<-myList$st
  sp<-myList$sp
  cg<-myList$cg
  if(sum(rs@env=="sqr70")<1)
    stop("need at least 1 trial in the sqr70 open field")
  if(sum(rs@env=="rest")<1)
    stop("need at least 1 trial in the rest box")

  ## make 2 spike-time autocorrelations
  st0<-spikeTimeAutocorrelation(st,binSizeMs = 1,
                                windowSizeMs = 20,probability = F)
  st1<-spikeTimeAutocorrelation(st,binSizeMs = 5,
                                windowSizeMs = 400,probability = F)

  ## get spikeTrain objects with intervals set to 2 different trials
  st.s1<-setIntervals(st,
                      s=getIntervalsEnvironment(rs,environment="sqr70")[1,1],
                      e=getIntervalsEnvironment(rs,environment="sqr70")[1,2])
  st.r<-setIntervals(st,
                     s=getIntervalsEnvironment(rs,environment="rest")[1,1],
                     e=getIntervalsEnvironment(rs,environment="rest")[1,2])

  ## get a speed filter to exclude immobility periods (possible swr)
  pt<-speedFilter(pt,minSpeed=3,maxSpeed=200)

  ## make 2 firing rate maps, different trials
  sp.s1<-firingRateMap2d(sp,st.s1,pt)
  sp.r<-firingRateMap2d(sp,st.r,pt)

  #########################################
  ### make summary figure with the data ###
  #########################################
  fileName=paste(rs@fileBase,".summary.pdf",sep="")
  print(paste("saving summary figure in",fileName))
  pdf(file = fileName ,paper = "a4", height = 10,width = 7.5) # open the file as device
  ## just need to make the figure now
  ncol=4
  nrow=8
  plot.per.page=ncol*nrow
  m<-matrix(c(rep(seq(0,1-(1/ncol),1/ncol),nrow),
              rep(seq(1/ncol,1,1/ncol),nrow),
              rep(seq(1-(1/nrow),0,0-1/nrow),each=ncol),
              rep(seq(1,1/nrow,0-1/nrow),each=ncol)),ncol=4)
  index=1
  nCells<-dim(sp.s1@maps)[3]
  for (i in 1:nCells){
    if(index==1)
    {
      split.screen(m)
    }
    screen(index)
    spikeTimeAutocorrelationPlot(x=st0@autoTimePoints,
                                 y=st0@auto[,i],type='l',
                                 name = paste(rs@session,st@cellList[i]))
    screen(index+1)
    spikeTimeAutocorrelationPlot(x=st1@autoTimePoints,
                                 y=st1@auto[,i],type='l',
                                 name= paste("tet:",cg@tetrode[i],"clu:",cg@cluToTetrode[i]))
    screen(index+2)
    firingRateMapPlot(sp.s1@maps[,,i],name=sp.s1@cellList[i],outma = c(0,3,0.5,3))
    screen(index+3)
    firingRateMapPlot(sp.r@maps[,,i],name=sp.r@cellList[i],outma = c(0,3,0.5,3))
    
    index=index+4 # next plot
    if((index-1)==plot.per.page)
    {
      close.screen( all.screens = TRUE )
      index=1
    }
  }
  close.screen(all.screens = TRUE)
  dev.off() # close the file as device
}

```

When called, the function generates a pdf file with information regarding the recorded cells.
You can modify the function to show the most relevent data for your project.
